# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("it_mgmt", "0006_auto_20150917_1454")]

    operations = [
        migrations.AlterModelOptions(
            name="computer", options={"base_manager_name": "objects"}
        ),
        migrations.AlterModelOptions(
            name="computerflag",
            options={"base_manager_name": "objects", "ordering": ["verbose_name"]},
        ),
        migrations.AlterModelOptions(
            name="ipaddress",
            options={
                "base_manager_name": "objects",
                "verbose_name": "IP Address",
                "verbose_name_plural": "IP Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="licence", options={"base_manager_name": "objects"}
        ),
        migrations.AlterModelOptions(
            name="networkinterface",
            options={"base_manager_name": "objects", "ordering": ("-primary", "name")},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"base_manager_name": "objects", "get_latest_by": "created"},
        ),
        migrations.AlterModelOptions(
            name="statuskey",
            options={"base_manager_name": "objects", "ordering": ["verbose_name"]},
        ),
        migrations.AlterModelOptions(
            name="worknote",
            options={"base_manager_name": "objects", "ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="computer",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="office_mgmt.Asset",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text='Only people with the "asset-owner" flag are shown',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="places.Room",
            ),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="ip_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="it_mgmt.IPAddress",
                verbose_name="IP Address",
            ),
        ),
    ]
