# Generated by Django 2.0.2 on 2018-02-28 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("it_mgmt", "0007_auto_20170602_1056")]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="office_mgmt.Asset",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="flags",
            field=models.ManyToManyField(
                blank=True, limit_choices_to={"active": True}, to="it_mgmt.ComputerFlag"
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text='Only people with the "asset-owner" flag are shown',
                limit_choices_to={"active": True, "flags__slug": "asset-owner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="room",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="places.Room",
            ),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="ip_address",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="it_mgmt.IPAddress",
                verbose_name="IP Address",
            ),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="type",
            field=models.CharField(
                choices=[
                    ("e", "Ethernet"),
                    ("w", "Wi-Fi"),
                    ("b", "Bluetooth"),
                    ("t", "Thunderbolt"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="statuskey",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("r", "raw"),
                    ("dt", "datetime"),
                    ("du", "disk usage"),
                    ("i", "int"),
                    ("f", "float"),
                    ("m", "memory"),
                    ("p", "percentage"),
                ],
                default="r",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="worknote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
